# preload = /home/domenik1023/Pictures/Background.png
# wallpaper = , /home/domenik1023/Pictures/Background.png

wallpaper {
    monitor = 
    path = /home/domenik1023/Pictures/Background.png
    fit_mode = cover
}